# Generated by Django 5.1.2 on 2024-11-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0001_initial'),
    ]

    operations = [
    ]
