# Generated by Django 5.1.2 on 2024-11-28 20:38

import Intern.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0010_remove_application_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_document',
            field=models.FileField(blank=True, null=True, upload_to=Intern.models.application_directory_path, validators=[Intern.models.validate_resumeFile_extension]),
        ),
    ]
