# Generated by Django 5.1.2 on 2024-10-24 10:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', cloudinary.models.CloudinaryField(max_length=255, verbose_name='flag_image')),
                ('continent', models.CharField(choices=[('Asia', 'ASIA'), ('Africa', 'AFRICA'), ('australia', 'AUSTRALIA'), ('antarctica', 'ANTARCTICA'), ('europe', 'EUROPE'), ('north_america', 'NORTH_AMERICA'), ('south_america', 'SOUTH_AMERICA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=200)),
                ('sub_major', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('education_level', models.CharField(choices=[('associate certificate', 'Associate certificate'), ("bachelor's degree", "Bachelor's Degree"), ("master's degree", "Master's Degree")], default="bachelor's degree", max_length=50)),
                ('requirements', models.TextField()),
                ('application_deadline', models.DateTimeField(auto_now_add=True)),
                ('posted_date', models.DateField()),
                ('company_logo', cloudinary.models.CloudinaryField(default='company_logo', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intern.country')),
                ('major_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Intern.major')),
            ],
        ),
    ]
