# Generated by Django 5.1.2 on 2024-10-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='application_deadline',
            field=models.DateTimeField(),
        ),
    ]
