# Generated by Django 5.1.2 on 2024-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0002_alter_internship_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='education_level',
            field=models.CharField(choices=[('associate certificate', 'Associate certificate'), ("bachelor's degree", "Bachelor's Degree"), ("master's degree", "Master's Degree"), ('Phd degree', 'PHD Degree')], default="bachelor's degree", max_length=50),
        ),
    ]
