# Generated by Django 5.1.2 on 2024-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0003_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Asia', 'ASIA'), ('Africa', 'AFRICA'), ('Australia', 'AUSTRALIA'), ('Antarctica', 'ANTARCTICA'), ('Europe', 'EUROPE'), ('North-america', 'NORTH_AMERICA'), ('South-america', 'SOUTH_AMERICA')], max_length=50),
        ),
    ]
