# Generated by Django 5.1.2 on 2024-11-06 02:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0003_alter_internship_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='major_name',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='requirements',
        ),
        migrations.AddField(
            model_name='internship',
            name='about_company',
            field=models.TextField(default='say something about company'),
        ),
        migrations.AddField(
            model_name='internship',
            name='benefits',
            field=models.TextField(default='what does the student gain?'),
        ),
        migrations.AddField(
            model_name='internship',
            name='job_description',
            field=models.TextField(default='describe th job details'),
        ),
        migrations.AddField(
            model_name='internship',
            name='majors',
            field=models.TextField(default='list of majors expected'),
        ),
        migrations.AddField(
            model_name='internship',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='picture', max_length=255),
        ),
        migrations.AddField(
            model_name='internship',
            name='qualifications',
            field=models.TextField(default='minimum qualifications'),
        ),
        migrations.AddField(
            model_name='internship',
            name='responsibilities',
            field=models.TextField(default='in charge of?'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
