# Generated by Django 5.1.2 on 2024-11-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0004_remove_internship_major_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='applicant_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('max_applications', models.PositiveIntegerField(default=15)),
                ('Internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Intern.internship')),
            ],
        ),
    ]
