# Generated by Django 5.1.2 on 2024-11-07 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0005_internship_applicant_count_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='standard_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddqkfdqy8/image/upload/v1730976302/qjliy417egm4jxavpanl.png', max_length=255),
        ),
    ]
