# Generated by Django 5.1.2 on 2024-11-19 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0005_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(default='07-0000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='applications', to='Intern.documents'),
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(default='country', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('internship', 'applicant')},
        ),
    ]
