# Generated by Django 5.1.2 on 2024-11-20 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0006_application_contact_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL),
        ),
    ]
