# Generated by Django 5.1.2 on 2024-11-25 11:40

import Intern.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0008_remove_application_max_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to=Intern.models.user_directory_path, validators=[Intern.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=Intern.models.user_directory_path, validators=[Intern.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=Intern.models.user_directory_path, validators=[Intern.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='visa',
            field=models.FileField(blank=True, null=True, upload_to=Intern.models.user_directory_path, validators=[Intern.models.validate_file_extension]),
        ),
    ]
