# Generated by Django 5.1.2 on 2024-11-28 14:49

import Intern.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0009_alter_documents_admission_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.AddField(
            model_name='application',
            name='resume_document',
            field=models.FileField(blank=True, null=True, upload_to=Intern.models.user_directory_path, validators=[Intern.models.validate_file_extension]),
        ),
    ]
