# Generated by Django 5.1.2 on 2024-11-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0011_alter_application_resume_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('internship', 'student')},
        ),
    ]
